### PR TITLE
Update to Development Setup

### PR DESCRIPTION
**Pull request by burr-road**
Reformatted files and added pictures.  

I included both files. I haven't got the hang of picking and choosing which files go into a Pull request from within GitHub yet.  (It was easy in Eclipse and Azure...)

### CODE REVIEW

**Review by bcdady — COMMENTED** [review]
This all looks good to me. What's the rationale behind moving some files into ./Local/ ?

**Comment by corsacca** [comment]
Is this moving all local setup/dev related docs into one "Local" folder?

**Comment by burr-road** [comment]
I may not have the hang of using GitHub.  I only expected this pull request to have the changes to mobile-app-setup and theme-local-setup, plus the images folder.  I didn't think I submitted the changes to the folder structure from my fork to the main repository.

As more documents are added to the repository we need a way to group related ones together, so we don't get a gigantic jumble.  Since @corsacca  created the Hooks folder, I thought it would be good to separate the development local installation instructions.  The folder had been called "install" but I thought there might be too much overlap with topics about "hosting" so... at the last moment changed its name to "local".  I was actually thinking of changing it back to "install" because that is more obvious before sending in another Pull request - but it already seems to be here???

**Comment by corsacca** [comment]
@burr-road I've merged in the changes. 
I would call the folder "Local-Development-Setup" to add clarity

**Comment by burr-road** [comment]
@corsacca Maybe this is a bigger discussion.  I like clarity, but I *also* like short names, like "Hooks/" :-)  

For the moment I think we just need need some high level groupings and then add more levels if the folders become too crowded. Eventually have something like "Development/Local/Setup/" or since "Development" is assumed then: "Local/Setup/", "Setup/Local/", "Install/Local/", or for now just "Local/", "Setup/" or "Install/"?

As I mentioned, "Local/" was originally "Install/", and I was going to include "WPEngine-hosting.md" in it. However, I then thought maybe that file should be grouped with "hosting.md" in perhaps a "Hosting/" folder instead, and changed the Install/ folder's name to Local/ *just* before uploading the changes... (never a good time to make a change :-)

What do you think?

**Comment by corsacca** [comment]
I'll probably rename Hooks to Theme-Hooks
I don't think we need to create sub-folders yet, or really try to account for them at this point.
I'd go for Local-Setup.
Hosting can be its own folder.

**Pull request merged**
